# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-06 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablesfieldschanges',
            old_name='change',
            new_name='change0',
        ),
    ]
